inherit_from: .rubocop_todo.yml

inherit_gem:
  perx-rubocop:
    - default.yml

inherit_mode:
  merge:
    - Exclude

Metrics/BlockLength:
  Exclude:
    - '**/spec/**/*_spec.rb'

Rails:
  Enabled: false
