{
 "title": "Resource Utilisation Victoria Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_deployment_status_replicas,namespace)"
   },
   {
    "name": "deployment",
    "label": "Service",
    "query": "label_values(kube_deployment_status_replicas,deployment)"
   }
  ]
 },
 "panels": [
  {
   "title": "Deployment Replicas",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Replicas" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace=~\"$namespace\",deployment=~\"$deployment\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "CPU Requests/Limits",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "CPU" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\",container=~\"$deployment\"}) by (container)",
     "legendFormat": "Request:{{container}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=~\"$namespace\",container=~\"$deployment\"}) by (container)",
     "legendFormat": "Limit: {{container}}"
    }
   ]
  },
  {
   "title": "Memory Requests/Limits",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bytes", "label": "RAM" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\",container=~\"$deployment\"}) by (container)",
     "legendFormat": "Request:{{container}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=~\"$namespace\",container=~\"$deployment\"}) by (container)",
     "legendFormat": "Limit: {{container}}"
    }
   ]
  }
 ]
}