{
 "title": "Rails App Overview Victoria Metrics",
 "description": "Ruby on Rails Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(ruby_http_requests_total,namespace)"
   },
   {
    "name": "app",
    "label": "App",
    "query": "label_values(ruby_http_requests_total,app_kubernetes_io_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Request Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ruby_http_requests_total{namespace=~\"$namespace\",app_kubernetes_io_name=~\"$app\"}[2m]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ruby_http_duration_seconds_sum{namespace=~\"$namespace\",app_kubernetes_io_name=~\"$app\"}[2m])) / sum(rate(ruby_http_duration_seconds_count{namespace=~\"$namespace\",app_kubernetes_io_name=~\"$app\"}[2m]))",
     "legendFormat": "latency"
    }
   ]
  },
  {
   "title": "Request Per Second by Controller and Action",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ruby_http_duration_seconds_count{namespace=~\"$namespace\",app_kubernetes_io_name=~\"$app\"}[2m])) by (controller, action)",
     "legendFormat": "{{controller}}: {{action}}"
    }
   ]
  },
  {
   "title": "Latency by Controller and Action",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ruby_http_duration_seconds_sum{namespace=~\"$namespace\",app_kubernetes_io_name=~\"$app\"}[2m])) by (controller, action) / sum(rate(ruby_http_duration_seconds_count{namespace=~\"$namespace\",app_kubernetes_io_name=~\"$app\"}[2m])) by (controller, action)",
     "legendFormat": "{{controller}}: {{action}}"
    }
   ]
  },
  {
   "title": "Request Per Second by Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ruby_http_requests_total{namespace=~\"$namespace\",app_kubernetes_io_name=~\"$app\"}[2m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "HTTP Error Rates as % Of Requests by Application",
   "type": "graph",
   "description": "HTTP Error Rates as % Of Requests by Application",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ruby_http_requests_total{namespace=~\"$namespace\",app=~\"$app\",status=~\"4.*|5.*\"})) by (app) / sum(rate(ruby_http_requests_total{namespace=~\"$namespace\",app=~\"$app\"})) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "HTTP Error Rates by Application",
   "type": "graph",
   "description": "HTTP Error Rates by Application",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ruby_http_requests_total{namespace=~\"$namespace\",app=~\"$app\",status=~\"4.*|5.*\"})) by (app,status) ",
     "legendFormat": "{{app}} : {{status}}"
    }
   ]
  }
 ]
}