{
 "title": "Cluster Overview",
 "description": "Overview of all pod & node resource requests, limits and usages",
 "tags": [
  "resources",
  "usage"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(eagle_node_resource_allocatable_cpu_cores{}, node)"
   }
  ]
 },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "CPU Cores" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{node=~\"$node\",resource=\"cpu\"})",
     "legendFormat": "Allocatable CPU Core"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{node=~\"$node\",resource=\"cpu\"} and on (pod) kube_pod_container_status_running >0)",
     "legendFormat": "Limits CPU Core"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{node=~\"$node\",resource=\"cpu\"} and on (pod) kube_pod_container_status_running > 0)",
     "legendFormat": "Requested CPU Core"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=~\"$node\",id=\"/\"}))",
     "legendFormat": "Usage CPU Cores"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 4, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=~\"$node\", id=\"/\"})) / sum(kube_node_status_allocatable{node=~\"$node\", resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{instance=~\"$node\",id=\"/\"})/sum(kube_node_status_allocatable{node=~\"$node\",resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "decbytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{node=~\"$node\",resource=\"memory\"})",
     "legendFormat": "Allocatable RAM"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{node=~\"$node\",resource=\"memory\"} and on (pod) kube_pod_container_status_running >0)",
     "legendFormat": "Requested RAM"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{node=~\"$node\",resource=\"memory\"} and on (pod) kube_pod_container_status_running >0)",
     "legendFormat": "Limit RAM"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{instance=~\"$node\",id=\"/\"})",
     "legendFormat": "Usage RAM"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Node CPU",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{node=~\"$node\",resource=\"cpu\"} and on (pod) kube_pod_container_status_running >0) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{node=~\"$node\", resource=\"cpu\"} and on (pod) kube_pod_container_status_running >0) by (node)"
    },
    {
     "expr": "sum(kube_node_status_allocatable{node=~\"$node\",resource=\"cpu\"}) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{node=~\"$node\",resource=\"cpu\"} and on (pod) kube_pod_container_status_running >0) by (node) / sum(kube_node_status_allocatable{node=~\"$node\",resource=\"cpu\"}) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{node=~\"$node.*\", resource=\"cpu\"} and on (pod) kube_pod_container_status_running >0) by (node) / sum(kube_node_status_allocatable{node=~\"$node.*\",resource=\"cpu\"}) by (node)"
    },
    {
     "expr": "label_replace(sum(rate(container_cpu_usage_seconds_total{id=\"/\"})) by (instance), \"node\", \"$1\", \"instance\", \"(.*)\") / on(node) sum(kube_node_status_allocatable{node=~\"$node.*\", resource=\"cpu\"}) by (node)"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Node RAM",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{node=~\"$node\",resource=\"memory\"} and on (pod) kube_pod_container_status_running >0) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{node=~\"$node\",resource=\"memory\"} and on (pod) kube_pod_container_status_running >0) by (node)"
    },
    {
     "expr": "sum(kube_node_status_allocatable{node=~\"$node\",resource=\"memory\"}) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{node=~\"$node\",resource=\"memory\"} and on (pod) kube_pod_container_status_running >0) by (node) / sum(kube_node_status_allocatable{node=~\"$node\",resource=\"memory\"}) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{node=~\"$node.*\", resource=\"memory\"} and on (pod) kube_pod_container_status_running >0) by (node) / sum(kube_node_status_allocatable{node=~\"$node.*\",resource=\"memory\"}) by (node)"
    },
    {
     "expr": "label_replace(sum(container_memory_working_set_bytes{instance=~\"$node\",id=\"/\"}) by (instance), \"node\", \"$1\", \"instance\", \"(.*)\") / on(node) sum(kube_node_status_allocatable{node=~\"$node.*\", resource=\"memory\"}) by (node)"
    }
   ]
  }
 ]
}