#!/usr/bin/env ruby

if ARGV[0]&.eql? '-T'
  res = %x(rake -T #{ARGV[1]})
  STDOUT.puts res.gsub(/^rake/, 'ros').gsub("\nrake", "\nros")
elsif ARGV[0]&.include? ':'
  require 'rake'
  tasks = ARGV.each_with_object([]) { |arg, tasks| tasks.append(arg) if arg.index(':') }
  args = ARGV.each_with_object([]) { |arg, args| args.append(arg) unless arg.index(':') }
  Rake.load_rakefile('Rakefile') if File.exists?('Rakefile')
  tasks.each { |task| Rake::Task[task].invoke(args) }
  # if ARGV[0]
  #   ENV['ROS_PROFILE'] = ARGV[0] # if action.eql?('setup')
  #   ENV['ROS_IMAGE'] = ARGV[0] # if action.eql?('apply')
  # end
else
  require 'bundler/setup'
  require 'ros'
  require 'ros/cli'
  Ros::Cli.start
end
